---
title: Rolly Cuizon
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Rolly Cuizon
markdown: kramdown
highlighter: rouge
exclude:
- node_modules
- gulpfile.js
- package.json
baseurl: ''
